config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  concern :voteable do
    resources :votes, only: :create
  end

  resources :posts, concerns: :voteable
  resources :comments, only: [:show, :create], concerns: :voteable
  delete :notifications, to: 'notifications#destroy'

  resources :users, only: [:show, :update, :edit]

  get 'digest/unsubscribe/:signature', to: 'digest#unsubscribe', as: :digest_unsubscribe

  root 'posts#index'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
  belongs_to :recipient, class_name: 'User'
  belongs_to :sender, class_name: 'User'
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!

  def destroy
    current_user.notifications.delete_all
    redirect_to :back
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_badge(notifications)
    render 'notifications/badge', notifications: notifications if notifications.count > 0
  end
end

app/views/notifications/_badge.html.erb
<span class="notification-badge">
  <%= notifications.count %>
</span>

app/views/notifications/_comment.html.erb
<div class="media-object notification align-middle small-image">
  <div class="media-prefix">
    <%= render 'shared/avatar', user: notification.sender %>
  </div>

  <div class="media-object">
    <p><%= notification.sender.name %> replied to your <strong><%= link_to 'comment', comment_path(notification.notifiable) %></strong>.</p>
  </div>
</div>

app/views/notifications/_notifications.html.erb
<div class="media-container media-header">
  <div class="media-object">
    <div class="media-body">
      <hgroup>
        <h1>Your notifications</h1>
        <%= link_to 'Delete them', notifications_path, method: :delete %>
      </hgroup>
    </div>
  </div>

  <% notifications.each do |notification| %>
    <%= render "notifications/#{notification.notifiable_type.downcase}", notification: notification %>
  <% end %>
</div>

app/views/notifications/_post.html.erb
<div class="media-object notification align-middle small-image">
  <div class="media-prefix">
    <%= render 'shared/avatar', user: notification.sender %>
  </div>

  <div class="media-body">
    <p><%= notification.sender.name %> commented on your <strong><%= link_to 'post', post_path(notification.notifiable) %></strong>.</p>
  </div>
</div>