config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  concern :voteable do
    resources :votes, only: :create
  end

  resources :posts, concerns: :voteable
  resources :comments, only: [:show, :create], concerns: :voteable
  delete :notifications, to: 'notifications#destroy'

  resources :users, only: [:show, :update, :edit]

  get 'digest/unsubscribe/:signature', to: 'digest#unsubscribe', as: :digest_unsubscribe

  root 'posts#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Tokenable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :votes
  has_many :notifications, foreign_key: 'recipient_id'

  validates :name, presence: true

  # Public: The avatar image url.
  #
  # Return either a gravatar image url or generated robot
  # url image via robothash.org
  #
  def avatar_url
    "http://robohash.org/#{email}?gravatar=yes"
  end

  def unsubscribe_digest!
    update_attribute(:send_digest, false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Settings updated'
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :send_digest)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-notice">Whoa there, something wasn't quite right. Have another crack at it.</div>
  <% end %>

  <%= f.text_field :name, autocomplete: 'off', placeholder: 'Name', class: :input %>

  <%= f.text_field :email, autocomplete: 'off', placeholder: 'Email', class: :input %>

  <div class="checkbox">
   <%= f.check_box :send_digest %> <%= f.label :send_digest, 'Send me a weekly digest', class: 'label inline' %>
  </div>

  <div class="media-object align-middle">
    <div class="media-body">
      Unhappy? <%= link_to "Cancel your account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %>
    </div>
    <%= f.submit 'Update', class: 'button button-right' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="media-container">
  <div class="media-object">
    <div class="media-body">
      <section>
        <h1><%= link_to @user.name, user_path(@user) %></h1>
        <% if @user == current_user %>
          <nav class="sub">
            <ul>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :get %></li>
              <li><%= link_to 'Settings', edit_user_path %></li>
              <li><%= link_to 'Change Password', edit_user_registration_path %>
            </ul>
          </nav>
        <% end %>
      </section>
    </div>

    <% unless @user == current_user %>
      <div class="media-image">
        <%= render 'shared/avatar', user: @user %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'notifications/notifications', notifications: @user.notifications if @user == current_user && @user.notifications.any? %>

<% if @user.posts.any? %>

  <div class="media-object media-header">
    <div class="media-body">
      <hgroup>
        <h1>Your posts</h1>
      </hgroup>
    </div>
  </div>

  <%= render 'posts/posts', posts: @user.posts %>
<% end %>