config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  concern :voteable do
    resources :votes, only: :create
  end

  resources :posts, concerns: :voteable
  resources :comments, only: [:show, :create], concerns: :voteable
  delete :notifications, to: 'notifications#destroy'

  resources :users, only: [:show, :update, :edit]

  get 'digest/unsubscribe/:signature', to: 'digest#unsubscribe', as: :digest_unsubscribe

  root 'posts#index'
end

app/views/shared/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-51711911-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_avatar.html.erb
<figure class="avatar">
  <%= link_to user_path(user.id) do %>
    <%= image_tag user.avatar_url %>
  <% end %>
</figure>

app/views/shared/_flash_messages.html.erb
<section class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-notice">
      <%= value %>
    </div>
  <% end %>
</section>

app/views/shared/_header.html.erb
<section class="container">
  <header>
    <div data-click="/" class="brand">
      <div class="logo"></div>
      <hgroup>
        <h1>the welly wag</h1>
        <p>wellington's community news</p>
      </hgroup>
    </div>

    <%= render 'shared/navigation' %>
  </header>
</section>

app/views/shared/_navigation.html.erb
<nav class="main">
  <ul>
    <% if current_user %>
      <li>
        <%= notification_badge(current_user.notifications) if current_user.notifications.any? %>
        <%= link_to 'profile', user_path(current_user) %>
      </li>
      <li><%= link_to 'new post', new_post_path, class: 'button' %></li>
    <% else %>
      <li><%= link_to 'log in', new_user_session_path %></li>
      <li><%= link_to 'join', new_user_registration_path, class: 'button' %></li>
    <% end %>
  </ul>
</nav>