config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  concern :voteable do
    resources :votes, only: :create
  end

  resources :posts, concerns: :voteable
  resources :comments, only: [:show, :create], concerns: :voteable
  delete :notifications, to: 'notifications#destroy'

  resources :users, only: [:show, :update, :edit]

  get 'digest/unsubscribe/:signature', to: 'digest#unsubscribe', as: :digest_unsubscribe

  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId

  include Voteable
  include Rankable
  include Markdownable

  NOTIFICATION_MESSAGE = "You have a new comment on your post."

  friendly_id :title, use: :slugged

  paginates_per 10

  belongs_to :user
  has_many :comments
  has_many :notifications, as: :notifiable

  validates :title, presence: true
  validates :url, url: { allow_blank: true }
  validates :url, presence: true, if: Proc.new { |p| p.description.blank? }

  scope :ranked, -> { all.sort_by(&:ranking).reverse }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Clearable
  before_action :authenticate_user!, except: [:index, :show]
  clear_notifications :post, :show

  def index
    @posts = Kaminari.paginate_array(Post.ranked).page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.friendly.find(params[:id])
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to action: :show, id: @post.friendly_id
    else
      render :new
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
    authorize! :update, @post
  end

  def update
    @post = Post.friendly.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(id: @post.friendly_id), notice: 'Good stuff your post is much improved'
    else
      render :edit
    end
  end

  def destroy
    current_user.posts.friendly.find(params[:id]).delete
    redirect_to root_path
  end

  private

  def post_params
    params[:post].permit(
      :title,
      :url,
      :description
    )
  end
end

app/views/posts/_post.html.erb
<div class="media-object">
  <div class="media-prefix">
    <%= render 'votes/vote', resource: post %>
  </div>

  <div class="media-body">
    <hgroup>
      <h1><%= link_to post.title, post_path(id: post.friendly_id) %></h1>
      <%= link_to display_url(post), post.url, class: 'i', target: '_blank' if post.url? %>
    </hgroup>
    <div class="content">
      <%= post.short_description_html %>
    </div>
    <%= link_to 'Edit', edit_post_path(id: post.friendly_id) if current_user && current_user == post.user %>
  </div>

  <div class="media-image">
    <%= render 'shared/avatar', user: post.user %>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="posts">
  <% posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= form_for @post, html: { class: 'form' } do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-notice">Whoa there, that wasn't quite right. Have another crack at it.</div>
  <% end %>

  <%= f.text_field :title, placeholder: 'Post title', class: 'input' %>

  <% if @post.url? %>
    <%= f.url_field :url, placeholder: 'http://myawesomelink.co.nz', class: 'input' %>
  <% else %>
    <%= f.text_area :description, placeholder: 'Enter your comment. Play nice with others.' %>
  <% end %>

  <div class="media-object align-middle">
    <div class="media-body">
      <span>Keep your edits to typos etc.</span>
    </div>
    <%= f.submit 'Update', class: 'button button-right' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= render 'posts/posts', posts: @posts %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="media-container">
  <div class="media-object">
    <div class="media-body">
      <p>Try to keep posts relevant. Think about what the Wellington community would like to see or hear. For example posting a link to show off your work or an interesting tidbit of local news. Alternatively posting a personal story or asking the community a topical question.</p>
    </div>
  </div>
</div>

<%= form_for @post, html: { class: 'form' } do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-notice">Whoa there, that wasn't quite right. Have another crack at it.</div>
  <% end %>

  <%= f.text_field :title, placeholder: 'Post title', class: 'input' %>
  <%= f.url_field :url, placeholder: 'http://myawesomelink.co.nz', class: 'input' %>
  <span class="helper-text">Include a url and/or a comment</span>
  <%= f.text_area :description, placeholder: 'Enter your comment. Play nice with others.' %>
  <div class="media-object align-middle">
    <div class="media-body">
      <span>You can use markdown</span>
    </div>
    <%= f.submit 'Share', class: 'button button-right' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="media-container">
  <div class="media-object">
    <div class="media-prefix">
      <%= render 'votes/vote', resource: @post %>
    </div>

    <div class="media-body">
      <hgroup>
        <h1><%= link_to @post.title, post_path(@post) %></h1>
        <%= link_to display_url(@post), @post.url, class: 'i', target: '_blank' if @post.url? %>
      </hgroup>

      <div class="content">
        <%= @post.description_html %>
      </div>
      <%= link_to 'Edit', edit_post_path(id: @post.friendly_id) if current_user && current_user == @post.user %>
    </div>

    <div class="media-image">
      <%= render 'shared/avatar', user: @post.user %>
    </div>
  </div>
</div>

<%= render 'comments/form', post: @post, parent: @post %>

<div class="comments">
  <%= render 'comments/comments', comments: @post.comments.root.ranked %>
</div>